server:
  port: 8082
  error:
    include-message: always


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/banco_db
    username: postgres
    password: p.123456
    properties:
      dialect: POSTGRES
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    platform: postgres
  data:
    jpa:
      show-sql: true
    r2dbc:
      repositories:
        enabled: true


logging:
  level:
    org:
      springframework: info
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org.springframework.data.r2dbc: DEBUG